# Generated by Django 3.2.3 on 2021-07-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='b_Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('em', models.TextField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='em',
        ),
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
    ]
