# Generated by Django 3.1.7 on 2021-05-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_login_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
