# Generated by Django 3.2.3 on 2021-07-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210727_1415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
