# Generated by Django 3.2.3 on 2021-07-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b_post',
            name='em',
        ),
    ]
